apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-logs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/kacper/Docker/kubernetes/obs/prometheus/logs