apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-logs
  finalizers: []
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi